# Configure keepalived on control plane nodes
---
- name: Configure keepalived
  hosts: control_plane
  become: true
  tasks:
    - name: Apply keepalived role
      ansible.builtin.include_role:
        name: keepalived
      when: keepalived_enabled | default(false) | bool
