# Deploy Longhorn
---
- name: Deploy Longhorn
  hosts: control_plane[0]
  become: true
  tasks:
    - name: Apply longhorn role
      ansible.builtin.include_role:
        name: longhorn
      when: longhorn_enabled | default(false) | bool
