# Deploy MetalLB
---
- name: Deploy MetalLB
  hosts: control_plane[0]
  become: true
  tasks:
    - name: Apply metallb role
      ansible.builtin.include_role:
        name: metallb
      when: metallb_enabled | default(false) | bool
