# tasks file for nginx-proxy-manager
---
- name: Create NPM namespace
  ansible.builtin.command: kubectl create namespace {{ npm_namespace }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  delegate_to: "{{ first_cp_hostname }}"
  run_once: true
  changed_when: true
  ignore_errors: true

- name: Deploy Nginx Proxy Manager
  ansible.builtin.shell: |
    cat <<EOF | kubectl apply -n {{ npm_namespace }} -f -
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: npm-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-proxy-manager
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nginx-proxy-manager
      template:
        metadata:
          labels:
            app: nginx-proxy-manager
        spec:
          containers:
            - name: nginx-proxy-manager
              image: jc21/nginx-proxy-manager:latest
              ports:
                - containerPort: 80
                - containerPort: 443
                - containerPort: {{ npm_admin_port }}
              volumeMounts:
                - name: data
                  mountPath: /data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: npm-data
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx-proxy-manager
    spec:
      type: LoadBalancer
      selector:
        app: nginx-proxy-manager
      ports:
        - name: http
          port: 80
          targetPort: 80
        - name: https
          port: 443
          targetPort: 443
        - name: admin
          port: {{ npm_admin_port }}
          targetPort: {{ npm_admin_port }}
    EOF
  args:
    executable: /bin/bash
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  delegate_to: "{{ first_cp_hostname }}"
  run_once: true
  changed_when: true
